language: node_js
node_js:
- stable
sudo: false
cache:
  yarn: true
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install --no-lockfile
script:
- yarn test
notifications:
  email: false
  slack:
    rooms:
      secure: WShDyt/M/6jBOTCEQhkJLe2pT0WzyjtBz4hWjDlABaNCYTUwqkkhiQJR9As6FuSvCHxh58bMcdPYolNW6glzY3IBV5YFojHZoehtUx7IRaOg722UEHJqm1cPhr5PXMPHUhcq3l8elpx0Vqv752gxlMyS+mjYywVvwgOjvVbs2BxpCJLsKcBHl78XZ2DVHobfi0ff5KwFd4jYnzt2BN9tK/HizC51OnRHbBj14bN4lPpgxvHTLLKjxLM2sVRXzusjgk6ETiODYibLWfYqRXHOdfDgIio2/F7F0daL91Pr2f4pDsAyFoUUB9q6HsozOsRB0ywLsjDba0DQhHupIro9JRNfj2/0sC8fjManUd9r1ws8H5xvJ1vAEk1autvzb1HYZGAuY86MY4LHeqK7V25pb1a51+ao5JnqBPl/5aHb1Z3OTmueWYc20o2rj0R40Vks2PjaUfJMKt6E4/1dW0mMrGOXnuE0hE6TvzZOKdsJgtz9FdfVWQOXliQ0T28rzH4PzdO7ma0G4wDQ3KNiQ6kE+DRi1KJ9oCgWzLdQQMcmo8nNS7mQAML3J0HAUAuHktbTIiivnJGbB0h3DnDJh7nfdqev4cRP8ZqZOufcsID9EfPzKn5CR8QBivMYDbVeN/hvrQorG6w8hLJ3QAyN96IbU9sS9l9YbDwf+5F5qMsjScs=
